name = "SparseMaxFlowMinCut"
uuid = "fef5f63e-3127-485b-a566-af50329564a3"
authors = ["artur <artur.a.pessoa@gmail.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
